### ISSUE TITLE
cache dotnet-install mv paa CI servere (perf)

### ISSUE THREAD

**Issue by maxild** [maxild/Skat#8]

**Comment by maxild** [comment]
On Travis

```yaml
cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine
```

On AppVeyor

```yaml
cache:
- tools -> build.cake
- packages -> build.cake
```
